"use strict";
exports.__esModule = true;
var did_key_creator_1 = require("did-key-creator");
var varint = require("varint");
var base58_1 = require("multiformats/bases/base58");
var raffiki = require("/home/ubuntu/Downloads/nov22nd/js-ceramic/packages/key-did-resolver/lib/index.js");
//import('/home/ubuntu//Downloads/nov22nd/js-ceramic/packages/key-did-resolver/lib/index.js');
var multicodecName = 'p256-pub';
var rawKey = 'f9c36f8964623378bdc068d4bce07ed17c8fa486f9ac0c2613ca3c8c306d7bb61cd36717b8ac5e4fea8ad23dc8d0783c2318ee4ad7a80db6e0026ad0b072a24f';
var compressedKey = (0, did_key_creator_1.compressedKeyInHexfromRaw)(rawKey);
var didkey = (0, did_key_creator_1.encodeDIDfromHexString)(multicodecName, compressedKey);
var splitkey = didkey.split(':');
var didkeyid = splitkey[2];
console.log(didkeyid);
var multicodecPubKey = base58_1.base58btc.decode(didkeyid);
console.log(multicodecPubKey);
var keyType = varint.decode(multicodecPubKey);
console.log(keyType);
var pubKeyBytes = multicodecPubKey.slice(varint.decode.bytes);
console.log(pubKeyBytes);
console.log(raffiki.nist_weierstrass_common.pubKeyBytesToHex(pubKeyBytes));
